title: [Spots]
description: [Find your perfect spot with Spots.]
github_repo: "https://github.com/manoa-spots/manoa-spots"


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
